#!/usr/bin/env bash
#
# replace_text
# https://github.com/koic/replace_text
#
# usage: replace_text pattern replacement [path]
#
function replace_text() {
    local target

    if [ $# -eq 2 ]; then
        target="ag -l $1"
    elif [ $# -eq 3 ]; then
        target="ls $3"
    else
        echo "usage: replace_text pattern replacement [path]" 1>&2

        return 1
    fi

    bash -c "$target | xargs sed -i -e \"s/$1/$2/g\""
}
